111:
  igp: "ospf"
  loopback_space: "2001:1:1:1::/64"
  networks_space: "2001:db8:1::/48"
  brand: "cisco"
  routers:
    R1:
      id: "1.1.1.1"
      ospf_area: 0
      interfaces:
        GigabitEthernet0/0:
          neighbour: "112:R2"
          bgp: "peer"
          addresses:
            - "2001:db8:1::1/128"
          
112:
  loopback_space: "2001:1:1:2::/64"
  networks_space: "2001:db8:2::/48"
  routers:
    R2:
      brand: "cisco"
      interfaces:
        GigabitEthernet0/0:
          neighbour: "111:R1"
          bgp: "peer"
          addresses:
            - "2001:db8:1::2/128"